"""empty message

Revision ID: 4f312a462222
Revises: 5913901d6c61
Create Date: 2025-02-11 08:08:58.496565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f312a462222'
down_revision = '5913901d6c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.alter_column('wall_side',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
        batch_op.alter_column('orientation',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('warehouse_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('uq_racks_name', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_racks_name', ['name'])
        batch_op.alter_column('warehouse_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('orientation',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('wall_side',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)

    # ### end Alembic commands ###
