"""empty message

Revision ID: 5913901d6c61
Revises: eb9ed01ff124
Create Date: 2025-02-05 22:18:47.661304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5913901d6c61'
down_revision = 'eb9ed01ff124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=20), nullable=True))
        batch_op.alter_column('wall_side',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
        batch_op.alter_column('orientation',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('warehouse_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint('uq_racks_name', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('warehouse_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('orientation',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('wall_side',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
        batch_op.drop_column('name')

    # ### end Alembic commands ###
