"""Add wall_side and facing_direction to Rack

Revision ID: 5dbdd1b0aab2
Revises: faf9ab444d88
Create Date: 2025-01-31 10:23:14.369444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dbdd1b0aab2'
down_revision = 'faf9ab444d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wall_side', sa.Enum('top-left', 'top-right', 'bottom', 'left', 'right', name='wall_side_enum'), nullable=False))
        batch_op.add_column(sa.Column('position', sa.Enum('horizontal', 'vertical', name='position_enum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('racks', schema=None) as batch_op:
        batch_op.drop_column('position')
        batch_op.drop_column('wall_side')

    # ### end Alembic commands ###
