"""Rack model.

Revision ID: eb9ed01ff124
Revises: 0edcb8101bb3
Create Date: 2025-02-04 11:15:53.766976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb9ed01ff124'
down_revision = '0edcb8101bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('racks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shelves', sa.Integer(), nullable=False),
    sa.Column('wall_side', sa.Enum('top-left', 'top-right', 'bottom', 'left', 'right', name='wall_side_enum'), nullable=False),
    sa.Column('orientation', sa.Enum('horizontal', 'vertical', name='position_enum'), nullable=False),
    sa.Column('position', sa.String(length=20), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('shelves BETWEEN 1 AND 10', name='check_shelves_limit'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position')
    )
    op.create_table('rack_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pallet_number', sa.String(length=50), nullable=True),
    sa.Column('content_type', sa.Enum('couch', 'pallet', name='content_type_enum'), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rack_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rack_contents')
    op.drop_table('racks')
    # ### end Alembic commands ###
