"""Create racks table

Revision ID: faf9ab444d88
Revises: 0edcb8101bb3
Create Date: 2025-01-30 10:21:39.575179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faf9ab444d88'
down_revision = '0edcb8101bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('racks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shelves', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('shelves BETWEEN 1 AND 10', name='check_shelves_limit'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rack_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pallet_number', sa.String(length=50), nullable=True),
    sa.Column('content_type', sa.Enum('couch', 'pallet', name='content_type_enum'), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rack_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rack_contents')
    op.drop_table('racks')
    # ### end Alembic commands ###
